### ISSUE TITLE
Document road to 1.0 release

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/sphinxcontrib-confluencebuilder#116]
Package has been out for a while, get's >10k downloads a year, has minimal bugs.

I think we should declare it "stable" and bless it with a 1.0 release.

This issue is to document immediate issues that should be closed before a 1.0 release

**Comment by tonybaloney** [comment]
@jdknight

**Comment by jdknight** [comment]
If there is a desire to make a 1.0 release, that works for me. Some notables:
- I would prefer (depending on your planned timeline) to add a simple glossary validation test to help verify some glossary changes (merged in from "next"). Just want to make sure there is no issues with building/publishing to a cloud and server instance with some versions.
- I assume you may have some desire changes to make based on a comment you have made in #96. Is that correct?
- It would be nice to get #110 completed as well.

As for the issues tagged in the milestone [0.10 release](https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/milestone/4); maybe this milestone can be renamed to, let us say, "0.1.1"? When I can, my goal has been to address auto-doc support (#51), but I doubt it would make it or be desired in a 1.0 stable release. I have been slowly re-writing the translator to support storage format instead of a Wiki-based format (the existing indentation support and storage-conversion stage make formatting a pain). While I am slowly making progress, I doubt it would be ready for review until August 2018.

**Comment by jdknight** [comment]
Closing in lieu of #171.
