### ISSUE TITLE
Strange behavior when trying to build a specific file.

### ISSUE THREAD

**Issue by sabinlinden** [tonybaloney/sphinxcontrib-confluencebuilder#65]
So currently the command I keep using over and over to build and push our package of documentation looks like this:
```
sphinx-build -b confluence -d _build/doctree . _build/htm -E -a
```

Admittedly, I was given this package of files (and this command, minutes the confluence part) by someone else and don't have intimate knowledge of how much of this is standard. The two directories listed contain doctree and conf files matching the .rst files in the base directory.

In any case, this command currently works well with 0.8 of confluencebuilder (minus the tilde/ampersand issue reported elsewhere) until I try to specify a file for building. When I try to run the following:
```
#(Tutorial can be swapped out for any other rst file in the base dir)
sphinx-build -b confluence -d _build/doctree . _build/htm -E tutorial.rst
```
I get an error that looks like this:
```
sphinxcontrib.confluencebuilder error:
---
An unsupported Confluence API call has been made.

REQ: PUT
RSP: 400
URL: https://lindenlab.atlassian.net/wiki/rest/api/
API: content
MSG: Could not update Content of type : class com.atlassian.confluence.pages.Page with id 174588341
---
```
Thankfully I think we're past the point where I have any other strange formatting errors that require me to look at specific files but it's very strange that I (new with 0.8) get this error when trying to build a specified file. Am I doing something wrong or does this look like a bug that needs fixing?

**Comment by jdknight** [comment]
@sabinlinden, are you using the `confluence_purge` option in your setup?

Truthfully, I've rarely ever attempted to publish a single document at a time. I can definitely see an issue when single-page publishing with the purge option -- the extension will remove all other pages not part of the publish attempt. While some scenarios may want this, I personally don't think it's ideal. Maybe there should be an option to check (if possible) if not the entire set of documents are being published. If so, do not allow purging to occur (if configured).

That being said, since purging happens after any pages are added/updated, I don't see why that would be an immediate issue for you. The message provided reports an error 400 for a page update request. Atlassian documentation for [Update Content](https://developer.atlassian.com/cloud/confluence/rest/#api-content-id-put) indicates that a "bad request" has either a bad `type` (which is shouldn't, since both new/update requests explicitly configure this value to `page`) or a required parameter is missing. The parameters listed; version, type, title; appear to be set appropriately. I'm curious to know the explicitly name for your title for the `tutorial.rst` document. Maybe the title value being used is not compatible with Atlassian Confluence (speculation)? If so, maybe there's some more sanity checking we can do for document titles (during pre-building).

**Comment by sabinlinden** [comment]
I do not have the confluence_purge flag anywhere. The error happens when I try to upload any individual rst, I just used tutorial as an example. This didn't happen in .7 but began in .8. We're using Confluence Cloud so it's always possible they updated something and it could just be coincidental timing. I'll see if I can get a better understanding of what's going on between -a usage and specific file calling.

**Comment by jdknight** [comment]
@sabinlinden, any news?

**Comment by jdknight** [comment]
Since there hasn't been an update in awhile, I'm going to mark this issue as closed. Feel free to open up a new issue if you're able to reproduce your unexpected state again.
